version: "3.2"
services:
  jupyter:
    image: agh/um-lime
    container_name: um-lime
    volumes:
      - type: "bind"
        source: ./
        target: /opt/notebooks
    ports:
      - 8888:8888
